"""Emails Models"""

from .emails import ScheduleDto
from .emails import ScheduleFetchSuccessfulDTO
from .emails import InvalidLocationDTO
from .emails import NotFoundDTO
from .emails import CreateBuilderDto
from .emails import CreateBuilderSuccesfulResponseDto
from .emails import FetchBuilderSuccesfulResponseDto
from .emails import DeleteBuilderSuccesfulResponseDto
from .emails import TemplateSettings
from .emails import IBuilderJsonMapper
from .emails import SaveBuilderDataDto
from .emails import BuilderUpdateSuccessfulDTO
from .emails import UpdateEmailTemplateDto
from .emails import UpdateEmailTemplateResponseDto
from .emails import BuilderElementNodePublicV2Dto
from .emails import BuilderEditorContentPublicV2Dto
from .emails import BuilderAttributePublicV2Dto
from .emails import BuilderCustomFlagsPublicV2Dto
from .emails import BuilderNodeAttrsPublicV2Dto
from .emails import CreateTemplatePublicV2BodyDto
from .emails import CreateTemplatePublicV2ResponseDto
from .emails import ImportTemplatePublicV2BodyDto
from .emails import ImportTemplatePublicV2ResponseDto
from .emails import CreateTemplateFolderPublicV2BodyDto
from .emails import CreateTemplateFolderPublicV2ResponseDto
from .emails import TemplateListItemPublicV2Dto
from .emails import ListTemplatesPublicV2ResponseDto
from .emails import GetTemplatePublicV2ResponseDto
from .emails import DeleteTemplatePublicV2ResponseDto
from .emails import UpdateTemplatePublicV2BodyDto
from .emails import UpdateTemplatePublicV2ResponseDto
from .emails import EmailStatsNumbersDto
from .emails import GetCampaignStatsResponseDto
from .emails import EmailStatsNumbersPublicV2Dto
from .emails import GetCampaignStatsPublicV2ResponseDto
from .emails import WorkflowCampaignPublicDto
from .emails import GetWorkflowCampaignsPublicResponseDto
from .emails import BulkActionCampaignEmailDetailsDto
from .emails import BulkActionCampaignDto
from .emails import GetBulkActionCampaignsResponseDto
from .emails import CreateEmailCampaignPublicV2BodyDto
from .emails import EmailCampaignVariationPublicV2Dto
from .emails import CreateEmailCampaignPublicV2ResponseDto
from .emails import EmailCampaignPublicV2Dto
from .emails import ListEmailCampaignsPublicV2ResponseDto
from .emails import UpdateEmailCampaignPublicV2BodyDto
from .emails import UpdateEmailCampaignPublicV2ResponseDto
from .emails import GetEmailCampaignPublicV2ResponseDto
from .emails import WorkflowCampaignPublicV2Dto
from .emails import ListWorkflowCampaignsPublicV2ResponseDto
from .emails import WorkflowCampaignSubSourcePublicV2Dto
from .emails import GetWorkflowCampaignPublicV2ResponseDto
from .emails import BulkActionCampaignPublicV2Dto
from .emails import ListBulkActionCampaignsPublicV2ResponseDto
from .emails import GetBulkActionCampaignPublicV2ResponseDto
from .emails import ScheduleCampaignEmailMetaPublicV2Dto
from .emails import ScheduleCampaignRecipientsPublicV2Dto
from .emails import ScheduleCampaignBatchConfigPublicV2Dto
from .emails import ScheduleCampaignTrackingPublicV2Dto
from .emails import ScheduleCampaignResendPublicV2Dto
from .emails import ScheduleCampaignScheduleConfigPublicV2Dto
from .emails import ScheduleCampaignRssConfigPublicV2Dto
from .emails import ScheduleCampaignABTestVariationPublicV2Dto
from .emails import ScheduleCampaignABTestConfigPublicV2Dto
from .emails import ScheduleCampaignPublicV2BodyDto
from .emails import ScheduleCampaignPublicV2ResponseDto
from .emails import DeleteCampaignPublicV2ResponseDto
__all__ = ["ScheduleDto", "ScheduleFetchSuccessfulDTO", "InvalidLocationDTO", "NotFoundDTO", "CreateBuilderDto", "CreateBuilderSuccesfulResponseDto", "FetchBuilderSuccesfulResponseDto", "DeleteBuilderSuccesfulResponseDto", "TemplateSettings", "IBuilderJsonMapper", "SaveBuilderDataDto", "BuilderUpdateSuccessfulDTO", "UpdateEmailTemplateDto", "UpdateEmailTemplateResponseDto", "BuilderElementNodePublicV2Dto", "BuilderEditorContentPublicV2Dto", "BuilderAttributePublicV2Dto", "BuilderCustomFlagsPublicV2Dto", "BuilderNodeAttrsPublicV2Dto", "CreateTemplatePublicV2BodyDto", "CreateTemplatePublicV2ResponseDto", "ImportTemplatePublicV2BodyDto", "ImportTemplatePublicV2ResponseDto", "CreateTemplateFolderPublicV2BodyDto", "CreateTemplateFolderPublicV2ResponseDto", "TemplateListItemPublicV2Dto", "ListTemplatesPublicV2ResponseDto", "GetTemplatePublicV2ResponseDto", "DeleteTemplatePublicV2ResponseDto", "UpdateTemplatePublicV2BodyDto", "UpdateTemplatePublicV2ResponseDto", "EmailStatsNumbersDto", "GetCampaignStatsResponseDto", "EmailStatsNumbersPublicV2Dto", "GetCampaignStatsPublicV2ResponseDto", "WorkflowCampaignPublicDto", "GetWorkflowCampaignsPublicResponseDto", "BulkActionCampaignEmailDetailsDto", "BulkActionCampaignDto", "GetBulkActionCampaignsResponseDto", "CreateEmailCampaignPublicV2BodyDto", "EmailCampaignVariationPublicV2Dto", "CreateEmailCampaignPublicV2ResponseDto", "EmailCampaignPublicV2Dto", "ListEmailCampaignsPublicV2ResponseDto", "UpdateEmailCampaignPublicV2BodyDto", "UpdateEmailCampaignPublicV2ResponseDto", "GetEmailCampaignPublicV2ResponseDto", "WorkflowCampaignPublicV2Dto", "ListWorkflowCampaignsPublicV2ResponseDto", "WorkflowCampaignSubSourcePublicV2Dto", "GetWorkflowCampaignPublicV2ResponseDto", "BulkActionCampaignPublicV2Dto", "ListBulkActionCampaignsPublicV2ResponseDto", "GetBulkActionCampaignPublicV2ResponseDto", "ScheduleCampaignEmailMetaPublicV2Dto", "ScheduleCampaignRecipientsPublicV2Dto", "ScheduleCampaignBatchConfigPublicV2Dto", "ScheduleCampaignTrackingPublicV2Dto", "ScheduleCampaignResendPublicV2Dto", "ScheduleCampaignScheduleConfigPublicV2Dto", "ScheduleCampaignRssConfigPublicV2Dto", "ScheduleCampaignABTestVariationPublicV2Dto", "ScheduleCampaignABTestConfigPublicV2Dto", "ScheduleCampaignPublicV2BodyDto", "ScheduleCampaignPublicV2ResponseDto", "DeleteCampaignPublicV2ResponseDto"]
