"""KnowledgeBase Models"""

from .knowledge_base import BadRequestDTO
from .knowledge_base import UnauthorizedDTO
from .knowledge_base import UnprocessableDTO
from .knowledge_base import InternalServerErrorDTO
from .knowledge_base import FaqResponseDTO
from .knowledge_base import ListFaqsResponseDTO
from .knowledge_base import AddFaqDTO
from .knowledge_base import CreateFaqResponseDTO
from .knowledge_base import UpdateFaqBodyDTO
from .knowledge_base import UpdateFaqResponseDTO
from .knowledge_base import DeleteFaqResponseDTO
from .knowledge_base import CrawledUrlDTO
from .knowledge_base import GetAllUrlsByKnowledgeBaseResponseDTO
from .knowledge_base import ErrorDetailsDTO
from .knowledge_base import CrawlingRecordDTO
from .knowledge_base import CrawlingAggregateDTO
from .knowledge_base import OperationDetailsDTO
from .knowledge_base import CrawlingStatusDataDTO
from .knowledge_base import CrawlingStatusResponseDTO
from .knowledge_base import DiscoverWebsiteRequestDTO
from .knowledge_base import DiscoverWebsiteDataDTO
from .knowledge_base import DiscoverWebsiteResponseDTO
from .knowledge_base import TrainDiscoveredUrlsDTO
from .knowledge_base import TrainDiscoveredUrlsResponseDTO
from .knowledge_base import DeleteWebsiteUrlRequestDTO
from .knowledge_base import DeleteWebsiteUrlResponseDTO
from .knowledge_base import KnowledgeBaseListItemDTO
from .knowledge_base import GetAllKnowledgeBasesPaginatedDataDTO
from .knowledge_base import GetAllKnowledgeBasesPaginatedResponseDTO
from .knowledge_base import KnowledgeBaseMetadataDTO
from .knowledge_base import GetKnowledgeBaseByIdDataDTO
from .knowledge_base import GetKnowledgeBaseByIdResponseDTO
from .knowledge_base import CreateKnowledgeBaseDTO
from .knowledge_base import KnowledgeBaseDataDTO
from .knowledge_base import CreateKnowledgeBaseResponseDTO
from .knowledge_base import UpdateKnowledgeBaseDTO
from .knowledge_base import UpdateKnowledgeBaseResponseDTO
from .knowledge_base import DeleteKnowledgeBaseResponseDTO
__all__ = ["BadRequestDTO", "UnauthorizedDTO", "UnprocessableDTO", "InternalServerErrorDTO", "FaqResponseDTO", "ListFaqsResponseDTO", "AddFaqDTO", "CreateFaqResponseDTO", "UpdateFaqBodyDTO", "UpdateFaqResponseDTO", "DeleteFaqResponseDTO", "CrawledUrlDTO", "GetAllUrlsByKnowledgeBaseResponseDTO", "ErrorDetailsDTO", "CrawlingRecordDTO", "CrawlingAggregateDTO", "OperationDetailsDTO", "CrawlingStatusDataDTO", "CrawlingStatusResponseDTO", "DiscoverWebsiteRequestDTO", "DiscoverWebsiteDataDTO", "DiscoverWebsiteResponseDTO", "TrainDiscoveredUrlsDTO", "TrainDiscoveredUrlsResponseDTO", "DeleteWebsiteUrlRequestDTO", "DeleteWebsiteUrlResponseDTO", "KnowledgeBaseListItemDTO", "GetAllKnowledgeBasesPaginatedDataDTO", "GetAllKnowledgeBasesPaginatedResponseDTO", "KnowledgeBaseMetadataDTO", "GetKnowledgeBaseByIdDataDTO", "GetKnowledgeBaseByIdResponseDTO", "CreateKnowledgeBaseDTO", "KnowledgeBaseDataDTO", "CreateKnowledgeBaseResponseDTO", "UpdateKnowledgeBaseDTO", "UpdateKnowledgeBaseResponseDTO", "DeleteKnowledgeBaseResponseDTO"]
